services:
  - type: web
    name: cardapio
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn cardapio.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cardapio_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"