services:
  - type: web
    name: cardapio
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn cardapio.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cardapio_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"
      - key: PRINT_MODE
        value: "impressao"  # APP, WEBHOOK ou TEST
      - key: PRINT_APP_DEEPLINK
        value: "bluetoothprinter://print?text="
      - key: PRINT_WEBHOOK_URL
        value: "https://api.seuappimpressora.com/print"