# Generated by Django 5.1.6 on 2025-04-21 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcarrinho',
            old_name='quntidade',
            new_name='quantidade',
        ),
    ]
