# Generated by Django 5.1.6 on 2025-04-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0003_rename_quntidade_itemcarrinho_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrinho',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
    ]
