# Generated by Django 5.1.6 on 2025-04-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0004_itemcarrinho_observacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='observacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
