# Generated by Django 5.1.6 on 2025-04-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0005_remove_itemcarrinho_observacoes_and_more'),
        ('produto', '0002_adicional_produto_disponivel_produtoadicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrinho',
            name='adicionais',
            field=models.ManyToManyField(blank=True, to='produto.adicional'),
        ),
    ]
