# Generated by Django 5.1.6 on 2025-05-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('acesso_admin', 'Pode acessar a área administrativa'), ('acesso_cliente', 'Pode acessar apenas como cliente')], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='tipo_cliente',
            new_name='tipo_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=100, verbose_name='nome completo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='telefone'),
        ),
    ]
