# Generated by Django 5.1.6 on 2025-04-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_cliente',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('ADMINISTRADOR', 'Administrador')], default='CLIENTE', editable=False, max_length=20),
        ),
    ]
