# Generated by Django 5.1.6 on 2025-04-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(blank=True, max_length=50, verbose_name='nome'),
        ),
    ]
