# Generated by Django 5.1.6 on 2025-04-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_tipo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_cliente',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('ADMINISTRADOR', 'Administrador')], default='CLIENTE', max_length=20),
        ),
    ]
