# Generated by Django 5.1.6 on 2025-05-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adicional',
            options={'ordering': ['nome'], 'verbose_name': 'Adicional', 'verbose_name_plural': 'Adicionais'},
        ),
        migrations.AlterModelOptions(
            name='categoriaproduto',
            options={'verbose_name': 'Categoria de Produto', 'verbose_name_plural': 'Categorias de Produtos'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='produtoadicional',
            options={'ordering': ['produto__nome', 'adicional__nome'], 'verbose_name': 'Adicional do Produto', 'verbose_name_plural': 'Adicionais dos Produtos'},
        ),
        migrations.AlterField(
            model_name='adicional',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Desmarque para ocultar este adicional', verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='adicional',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome do Adicional'),
        ),
        migrations.AlterField(
            model_name='adicional',
            name='preco_extra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Extra'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Desmarque para ocultar este produto do cardápio', verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='produto.categoriaproduto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produtoadicional',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Desmarque para desativar este adicional para o produto específico', verbose_name='Ativo?'),
        ),
    ]
