# Generated by Django 5.1.6 on 2025-04-27 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('preco_extra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ProdutoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('adicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.adicional')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adicionais', to='produto.produto')),
            ],
            options={
                'unique_together': {('produto', 'adicional')},
            },
        ),
    ]
