# Generated by Django 5.1.6 on 2025-05-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_adicional_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adicional',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categoriaproduto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='produtoadicional',
            options={},
        ),
        migrations.AlterField(
            model_name='adicional',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='adicional',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adicional',
            name='preco_extra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categorias',
            field=models.ManyToManyField(related_name='produtos', to='produto.categoriaproduto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produtoadicional',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
