# Generated by Django 5.1.6 on 2025-05-01 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='disponivel',
        ),
    ]
