# Generated by Django 5.1.6 on 2025-05-08 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('impresso', models.BooleanField(default=False)),
                ('data_impressao', models.DateTimeField(blank=True, null=True)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('ultimo_erro', models.TextField(blank=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impressao', to='pedido.pedido')),
            ],
            options={
                'verbose_name': 'Impressão',
                'verbose_name_plural': 'Impressões',
            },
        ),
    ]
