# Generated by Django 5.1.6 on 2025-05-05 23:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Bairro')),
                ('taxa', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Taxa de Entrega')),
                ('tempo', models.CharField(default='30-45 min', max_length=50, verbose_name='Tempo Estimado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LocalEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço Completo')),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.bairro', verbose_name='Bairro')),
            ],
            options={
                'verbose_name': 'Local de Entrega',
                'verbose_name_plural': 'Locais de Entrega',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_entrega', models.CharField(max_length=150, verbose_name='Endereço Completo')),
                ('referencia_entrega', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ponto de Referência')),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Taxa de Entrega')),
                ('data_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('preco_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Total')),
                ('forma_pagamento', models.CharField(choices=[('CREDITO', 'Cartão de Crédito'), ('DEBITO', 'Cartão de Débito'), ('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro')], max_length=20, verbose_name='Forma de Pagamento')),
                ('precisa_troco', models.BooleanField(default=False, verbose_name='Precisa de Troco?')),
                ('valor_troco_para', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Troco para (R$)')),
                ('numero_diario', models.PositiveIntegerField(default=1, verbose_name='Número do Pedido do Dia')),
                ('data_referencia', models.DateField(default=datetime.date.today, verbose_name='Data de Referência')),
                ('bairro_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedido.bairro', verbose_name='Bairro de Entrega')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-data_pedido'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('observacoes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observações')),
                ('adicionais', models.ManyToManyField(blank=True, to='produto.adicional')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.produto', verbose_name='Produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='pedido.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
    ]
