# Generated by Django 5.1.6 on 2025-05-05 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_referencia',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Referência'),
        ),
    ]
