# Generated by Django 5.1.6 on 2025-05-01 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_referencia',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Referência'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_diario',
            field=models.PositiveIntegerField(default=1, verbose_name='Número do Pedido do Dia'),
        ),
    ]
