# Generated by Django 5.1.6 on 2025-04-27 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_alter_itempedido_preco_unitario'),
        ('produto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bairro',
            options={'ordering': ['nome'], 'verbose_name': 'Bairro', 'verbose_name_plural': 'Bairros'},
        ),
        migrations.AlterModelOptions(
            name='localentrega',
            options={'verbose_name': 'Local de Entrega', 'verbose_name_plural': 'Locais de Entrega'},
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='preco',
        ),
        migrations.AddField(
            model_name='bairro',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Bairro'),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='taxa',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Taxa de Entrega'),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='tempo',
            field=models.CharField(default='30-45 min', max_length=50, verbose_name='Tempo Estimado'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='observacoes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='pedido.pedido', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='localentrega',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.bairro', verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='bairro_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedido.bairro', verbose_name='Bairro de Entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.CharField(max_length=150, verbose_name='Endereço Completo'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='preco_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='referencia_entrega',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ponto de Referência'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PROCESSANDO', 'Processando'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='PROCESSANDO', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='taxa_entrega',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Taxa de Entrega'),
        ),
    ]
