# Generated by Django 5.1.6 on 2025-05-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_pedido_data_referencia_pedido_numero_diario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('CREDITO', 'Cartão de Crédito'), ('DEBITO', 'Cartão de Débito'), ('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro')], default='PIX', max_length=20, verbose_name='Forma de Pagamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='precisa_troco',
            field=models.BooleanField(default=False, verbose_name='Precisa de Troco?'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_troco_para',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Troco para (R$)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(default='pendente', max_length=20),
        ),
    ]
