# Generated by Django 5.1.6 on 2025-05-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_pedido_forma_pagamento_pedido_precisa_troco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='status',
        ),
    ]
